# Generated by Django 2.0.5 on 2018-06-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20180623_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\PythonCourse\\SocialNetwork\x0cacebook\\Images'),
        ),
    ]
