# Generated by Django 2.0.5 on 2018-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20180624_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
