# Generated by Django 2.0.5 on 2018-07-07 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20180707_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 20, 17, 25)),
        ),
    ]
