# Generated by Django 2.0.5 on 2018-07-14 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_auto_20180710_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 18, 20, 32, tzinfo=utc)),
        ),
    ]
